customCommands:
  - key: "C"
    description: "Commit with czg"
    context: "files" # Only shows when on the Files view
    command: "czg"
    output: terminal
  - key: "A"
    description: "AI Commit with czg"
    context: "files"
    command: "czg ai"
    output: terminal
