require("items.spaces")
require("items.front_app")
require("items.calendar")
require("items.widgets.battery")
require("items.widgets.cpu")
require("items.widgets.ram")
require("items.widgets.notifications")
require("items.widgets.port_forwards")
